---
- assert:
    that:
      - consul_ansible_bootstrap_group_name is defined and consul_ansible_bootstrap_group_name|length > 0
    msg: "Variable 'consul_ansible_bootstrap_group_name' should be defined"

- assert:
    that:
      - secrets_dir is defined and secrets_dir|length > 0
    msg: "Variable 'secrets_dir' should be defined"

- import_tasks: _setup_user_and_group.yml

- import_tasks: _get_consul.yml

- import_tasks: _configure.yml

- import_tasks: _sys_integration.yml

- meta: flush_handlers
